### ISSUE TITLE
Bot is not actually open source

### ISSUE THREAD

**Issue by AleksiVirkkala** [KasperiP/kiderat-desktop#11]
I'm a bit annoyed that you advertise your bot as *"fully open-source"* while you use private api for `x-requested-id`.

And no I'm not jealous of the hidden code. It's here:

```ts
export function calculateXRequestedId(inventoryId: string): string {
	// Remove dashes from the inventory ID
	const strippedId = inventoryId.replace(/-/g, '');
	// An extra ID that will be XOR'd with the inventory ID
	const EXTRA_ID = '2ad64e4b26c84fbabba58181de76f7b0';

	// Initialize an empty string to store the final result
	let encodedString = '';

	// Loop through each character of the stripped inventory ID
	for (let i = 0; i < strippedId.length; i++) {
		// XOR the ASCII codes of the characters from strippedId and EXTRA_ID
		const xorResult = strippedId.charCodeAt(i) ^ EXTRA_ID.charCodeAt(i);

		// Append the character corresponding to the XOR result to the encoded string
		encodedString += String.fromCharCode(xorResult);
	}

	// Convert the encoded string to Base64 and return the first 10 characters
	return btoa(encodedString).substring(0, 10);
}
```

**Comment by KasperiP** [comment]
Indeed, that's true, and I was aware that the decision to do so was rather daring. I've now published the code. I had been anticipating someone to open an issue like this. Since this was the first time Kide took some steps to prevent botting, I believed it presented a valuable challenge for other developers to tackle the issue themselves, rather than resorting to mere copy-pasting solutions from other repositories, as it may not be truly beneficial for anyone.
