### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Lk991** [KasperiP/kiderat-desktop#14]
Im putting the auth token correctly into the loginscreen after downloading the app, still says that something went wrong. And I havent included the "" either.

**Comment by KasperiP** [comment]
Make sure you are using the latest version (v0.0.15). You can check your version from the bottom right corner on the first screen. I updated the bot today because Kide had some breaking API changes.

Kide also made some changes to their token implementation. I would recommend logging out and then logging back in to Kide to see if that fixes the issue. I just tested it myself, and the latest version seems to be working fine.

There is also updated guide for getting access token: https://www.kiderat.app/access-token

**Comment by Lk991** [comment]
Thank you, login out and back in seems to have fixed the issue.
